version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - app-network
  db:
    image: postgres:15
    restart: unless-stopped
    container_name: db
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  webserver:
    image: nginx:1.25
    restart: unless-stopped
    container_name: webserver
    depends_on:
      - php
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge

